package rules

import org.sapient.ruleengine.trade.model.TradeData;
import org.sapient.ruleengine.trade.model.TradeType;
import org.sapient.ruleengine.alarm.core.AlarmEventListener;
import org.sapient.ruleengine.events.FxTradeEvent;
import org.sapient.ruleengine.facts.FxTrade;

global  AlarmEventListener alarmEventListener;

rule "Buy Trade Amount is more than 1000"
when
	$buyTradeData : TradeData(tradeType == TradeType.BUY && amount > 1000)
then
	alarmEventListener.fireEvent(new FxTradeEvent("TradeBuyAmountRule violation!", new FxTrade($buyTradeData, null)));
end
