//created on: Mar 20, 2017
package com.rules.counter

import com.sample.model.Product;
import com.sample.model.ProductResult;
import com.sample.model.ProductType;

rule "Sum all products"
when
 $productType   : ProductType()
 $productResult : ProductResult() from accumulate(
         $pr : Product( productType == $productType, $p : price ),
         init( 
         	double total = 0;
         	ProductResult  productResult = new ProductResult(); 
         	System.out.println("Initilize-Enter");
         	),
         action( 
         	total += $p;
            productResult.setProduct($pr);
            productResult.setTotalPrice(total);
            System.out.println($pr); 
            ),
         reverse( total -= $p; ),
         result( productResult) )
then
 	System.out.println("$productResult: " + $productResult);
end

rule "find the number of product."
when
 $count : Number() from accumulate(
         Product( $p : price ),
         count( $p ) )
then
 	System.out.println("Total number of products=" + $count);
end


rule "find the minimum value of the product from list products."
when
 $minium : Number() from accumulate(
         Product( $p : price ),
         min( $p ))
then
 	System.out.println("Min price of products=" + $minium );
end

rule "find the maximum value of the product from list products."
when
 $maximum : Number() from accumulate(
         Product( $p : price ),
         max( $p ) )
then
 	System.out.println("Max price of products=" + $maximum);
end

rule "find the total sum of the all products."
when
 $total : Number() from accumulate(
         Product( $p : price ),
         sum( $p ) )
then
 	System.out.println("Total price of products=" + $total);
end

rule "find the average value of the products."
when
 $avg : Number() from accumulate(
         Product( $p : price ),
         average( $p ) )
then
 	System.out.println("Avg price of products= " + $avg);
end


