//created on: Mar 20, 2017

package com.rules.counter

import org.sapient.entites.trade.Trades.Trade;
import org.sapient.ruleengin.trade.WashTrade;
import org.sapient.FactProcessor;

global FactProcessor<Fact> factProcessor;
rule "Wash trade rule"
when
$buyTrade : Trade($security : security, $company : company, $quantity : quantity, tradeType == "BUY")

$sellTrade : Trade(security == $buyTrade.security
				&& company == $buyTrade.company 
				&& tradeType == "SELL"
				&& quantity == $buyTrade.quantity
				&& time == $buyTrade.time)
then
	factProcessor.process(new WashTrade($buyTrade, $sellTrade));
	delete($buyTrade);
	delete($sellTrade);
end

