package rules

import org.sapient.ruleengine.trade.model.TradeData;
import org.sapient.ruleengine.trade.model.TradeType;
import org.sapient.ruleengine.alarm.core.AlarmEventListener;
import org.sapient.ruleengine.events.FxTradeEvent;
import org.sapient.ruleengine.facts.FxTrade;

global  AlarmEventListener alarmEventListener;

/**rule "Count number of buy trades for same compnay and security is more than 48"
when
$buyTrade : TradeData($security : security, $company : company, tradeType == TradeType.BUY)

	 $count : Number($count > 48) from accumulate(
         $tradeData : TradeData(security == $buyTrade.security
				&& company == $buyTrade.company && tradeType == TradeType.BUY),
         count( $tradeData ) )
then
	alarmEventListener.fireEvent(new FxTradeEvent("Count number of buy trades for same compnay and security is more than 48 - violation!", new FxTrade($buyTrade, null)));
end*/
