package rules

import org.sapient.ruleengine.trade.model.TradeData;
import org.sapient.ruleengine.trade.model.TradeType;
import org.sapient.ruleengine.alarm.core.AlarmEventListener;
import org.sapient.ruleengine.events.FxTradeEvent;
import org.sapient.ruleengine.facts.FxTrade;

global  AlarmEventListener alarmEventListener;

/**rule "Count number of sell trades for same compnay is more than 100"
when
$sellTrade : TradeData($company : company, tradeType == TradeType.BUY)

	 $count : Number($count > 100) from accumulate(
         $tradeData : TradeData(company == $sellTrade.company && tradeType == TradeType.BUY),
         count( $tradeData ) )
then
	alarmEventListener.fireEvent(new FxTradeEvent("Count number of sell trades for same compnay is more than 100 - violation!", new FxTrade(null, $sellTrade)));
end*/
