package rules

import org.sapient.ruleengine.trade.model.TradeData;
import org.sapient.ruleengine.trade.model.TradeType;
import org.sapient.ruleengine.alarm.core.AlarmEventListener;
import org.sapient.ruleengine.events.FxTradeEvent;
import org.sapient.ruleengine.facts.FxTrade;

global  AlarmEventListener alarmEventListener;

rule "Sell Trade Quantity is more than 500"
when
	$sellTradeData : TradeData(tradeType == TradeType.SELL && quantity > 500)
then
	alarmEventListener.fireEvent(new FxTradeEvent("TradeSellQuantityRule violation!", new FxTrade(null, $sellTradeData)));
end
