package rules

import org.sapient.ruleengine.trade.model.TradeData;
import org.sapient.ruleengine.trade.model.TradeType;
import org.sapient.ruleengine.alarm.core.AlarmEventListener;
import org.sapient.ruleengine.events.FxTradeEvent;
import org.sapient.ruleengine.facts.FxTrade;

global  AlarmEventListener alarmEventListener;

rule "Sell Trade Amount is more than 5000"
when
	$buyTradeData : TradeData(tradeType == TradeType.SELL && amount > 5000)
then
	alarmEventListener.fireEvent(new FxTradeEvent("TradeSellAmountRule violation!", new FxTrade($buyTradeData, null)));
end
